//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class GlavnaTabela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GlavnaTabela()
        {
            this.Kontakts = new HashSet<Kontakt>();
        }

     
        public int IDPreduzeca { get; set; }

        [Display(Name = "Naziv preduzeća")]
        [Required(ErrorMessage = "Neophodno popuniti naziv preduzeća.")]
    
        public string NazivPreduzeca { get; set; }
        [Display(Name = "Adresa")]
        [Required(ErrorMessage = "Neophodno popuniti polje za adresu.")]
        public string AdresaRegistracijePreduzeca { get; set; }

        [Display(Name = "Opština")]
        [Required(ErrorMessage = "Neophodno popuniti polje za opštinu.")]
        public string Opstina { get; set; }

        [Display(Name = "Matični broj")]
        [Required(ErrorMessage = "Neophodno popuniti polje za matični broj.")]
        public string MaticniBrojPreduzeca { get; set; }

        [Display(Name = "PIB")]
        [Required(ErrorMessage = "Neophodno popuniti polje za PIB.")]
        public string PIB { get; set; }

        [Display(Name = "Broj računa")]
        [Required(ErrorMessage = "Neophodno popuniti polje za broj računa.")]
        public string BrRacuna { get; set; }

        [Display(Name = "Veb stranica")]
        [Required(ErrorMessage = "Neophodno popuniti polje za veb sajt.")]       
        public string WebStranica { get; set; }


        [Display(Name = "Pečat")]

        public  byte[] Fotografija { get; set; }


        
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "Beleška")]
        [Required(ErrorMessage = "Neophodno popuniti polje za belešku.")]
        public string Beleska { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontakt> Kontakts { get; set; }
    }
}
