//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KontaktTelefon
    {

        public int IDTel { get; set; }
        public int IDOsoba { get; set; }

        [Display(Name = "Tip")]
        [Required(ErrorMessage = "Neophodno popuniti polje za tip (Kancelarija, službeni,itd.")]
        public string OznakaTelefona { get; set; }

        [Display(Name = "Tip adrese")]
        [Required(ErrorMessage = "Neophodno popuniti polje za tip adrese.")]
       
        public string BrojTelefona { get; set; }

        [Display(Name = "Lokal")]
        [Required(ErrorMessage = "Neophodno popuniti polje za lokal.")]
        public string Lokal { get; set; }
    
        public virtual Kontakt Kontakt { get; set; }
    }
}
