//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KontaktMail
    {
        public int IDMail { get; set; }
       
        public int IDOsoba { get; set; }


        [Display(Name = "Tip adrese")]
        [Required(ErrorMessage = "Neophodno popuniti polje za tip adrese.")]
        public string OznakaPosla { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "Neophodno popuniti polje za email.")]
        [EmailAddress(ErrorMessage = "Pogrešna Email adresa.")]
        public string Adresa { get; set; }
    
        public virtual Kontakt Kontakt { get; set; }
    }
}
